const SPACECRAFTS = [
  "Corellian Corvette",
  "Death Star",
  // "Ebon Hawk",
  // "Geonosian solar sailer",
  // "Imperial Landing Craft",
  // "Lambda-class shuttle",
  "Millennium Falcon",
  // "Moldy Crow",
  // "Naboo royal cruiser",
  // "Naboo royal starship",
  // "Naboo star skiff",
  // "Nebulon-B frigate",
  // "Neimoidian shuttle",
  // "Outrider",
  // "Radiant VII",
  // "Raven's Claw",
  // "Rebel blockade runner",
  // "Republic assault ship",
  // "Republic attack cruiser",
  // "Republic cruiser",
  // "Rogue Shadow",
  // "Sith Infiltrator",
  // "Slave I",
  // "Star Destroyer",
  // "Starfreighter",
  // "Tantive IV",
  // "Techno Union Starship",
  // "Theta-class shuttle",
  // "Lucrehulk-class battleship",
  // "Trade Federation cruiser",
  // "Trade Federation landing ship",
  // "Virago",
  "TIE Fighter"
]

export default SPACECRAFTS